### ISSUE TITLE
Control panel closing error

### ISSUE THREAD

**Issue by charlespax** [makerbot/ReplicatorG#127]
When closing the control panel I sometimes get:

java.util.ConcurrentModificationException
    at java.util.Vector$Itr.checkForComodification(Vector.java:1119)
    at java.util.Vector$Itr.next(Vector.java:1096)
    at replicatorg.app.MachineController.emitStateChange(MachineController.java:830)
    at replicatorg.app.MachineController.setState(MachineController.java:75)
    at replicatorg.app.MachineController.setState(MachineController.java:86)
    at replicatorg.app.MachineController.access$500(MachineController.java:66)
    at replicatorg.app.MachineController$MachineThread.run(MachineController.java:467)

**Comment by kintel** [comment]
should be fixed by now.
