### ISSUE TITLE
Control panel fails to launch 029_r2 + reprap 1.2 + EC 2.2 (Makerbot Cupcake MK3 HBP)

### ISSUE THREAD

**Issue by mangelajo** [makerbot/ReplicatorG#262]
What steps will reproduce the problem?
1. Use a Makerbot EC/2.2 + RepRap 1.2 motherboard with last 3.0 firmware
2. Start replicator (linux or windows, tried ES and also US locales)
3. Connect
4. Try to open control panel

What is the expected output? What do you see instead?

Control panel won't open, in replicator console I see:

Packet response code: OK
Packet payload: 0

In linux console I see:

Feb 5, 2012 4:30:31 AM replicatorg.drivers.gen3.PacketResponse printDebug
INFO: Packet response code: OK
Feb 5, 2012 4:30:31 AM replicatorg.drivers.gen3.PacketResponse printDebug
INFO: Packet payload: 0
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cannot format given Object as a Number
at java.text.DecimalFormat.format(Unknown Source)
at java.text.Format.format(Unknown Source)
at javax.swing.text.InternationalFormatter.valueToString(Unknown Source)
at javax.swing.JFormattedTextField$AbstractFormatter.install(Unknown Source)
at javax.swing.text.DefaultFormatter.install(Unknown Source)
at javax.swing.text.InternationalFormatter.install(Unknown Source)
at javax.swing.JFormattedTextField.setFormatter(Unknown Source)
at javax.swing.JFormattedTextField.setValue(Unknown Source)
at javax.swing.JFormattedTextField.setValue(Unknown Source)
at replicatorg.app.ui.controlpanel.ExtruderPanel.<init>(ExtruderPanel.java:200)
at replicatorg.app.ui.controlpanel.ControlPanelWindow.createToolsPanel(ControlPanelWindow.java:255)
at replicatorg.app.ui.controlpanel.ControlPanelWindow.<init>(ControlPanelWindow.java:133)
at replicatorg.app.ui.controlpanel.ControlPanelWindow.getControlPanel(ControlPanelWindow.java:97)
at replicatorg.app.ui.MainWindow.handleControlPanel(MainWindow.java:1635)
at replicatorg.app.ui.MainWindow$25.actionPerformed(MainWindow.java:1089)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$000(Unknown Source)
at java.awt.EventQueue$1.run(Unknown Source)
at java.awt.EventQueue$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$2.run(Unknown Source)
at java.awt.EventQueue$2.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)

It may seem like a locale problem, but I tried setting en_US locale first, may be it's some incomaptibility of last firmware for my reprap1.2 electronics with the latest replicatorG? (I also tried 28 and I think 27),

What version of the product are you using? On what operating system?

029_r2, 028, and 027 (not sure), 026 won't move Z axis.
I tried in Ubuntu linux + sun jre and also in windows.

Please provide any additional information below.

I tried changing locale (. / , decimal point) in windows, and also tried es_EU and en_US locales, same error always.

**Comment by mangelajo** [comment]
It works for 031 BETA :-)
