### ISSUE TITLE
Null pointer excepting when Estimating build

### ISSUE THREAD

**Issue by rcarlsen** [makerbot/ReplicatorG#282]
When using an older machines.xml (ie. not one of the new "The Replicator" machine definitions but one such as "Cupcake Basic") a NullPointer exception is thrown.

Console:
INFO: Estimating...
Exception in thread "Estimation Thread" java.lang.NullPointerException
    at replicatorg.app.gcode.GCodeParser.buildGCodes(GCodeParser.java:654)
    at replicatorg.app.gcode.GCodeParser.parse(GCodeParser.java:243)
    at replicatorg.machine.Machine.estimate(Machine.java:497)
    at replicatorg.app.ui.MainWindow$EstimationThread.run(MainWindow.java:2586)

It seems that something in the tool head parsing is failing:
if (driver.getMachine().getTool(tool).getMotorStepperAxis().name() == "B") {

Here is the tool entity which seems to fail:

``` xml
<tool name="Mk5/6/6+" type="extruder" material="abs" floodcoolant="false" mistcoolant="false" fan="true" valve="false" collet="false" heater="true"  heatedplatform="true" motor_steps="3200" stepper_axis="a"/>
```

Modifying this entry to be more similar to the entity in "The Replicator" machine definition avoids the crash:

``` xml
<tool name="Mk6+" model="Mk6" diameter="0.4" stepper_axis="a" index="0" type="extruder" motor="true" material="abs" fan="true" heater="true" heatedplatform="true" motor_steps="3200"/>
```

**Comment by stevenrose** [comment]
This is the error i see currently, can you tell me what to change in the machine definitions to get it running?

**Comment by rcarlsen** [comment]
I modified the <tool ... /> entity to contain attributes similar to the MakerBot-provided Replicator machine definition. I don't have my configuration in front of me at the moment. Not sure what happened to my above comment—I had originally provided the examples. (Edit: fixed the above comment to display the code examples)

**Comment by bwbeach** [comment]
I'm having the same problem.  It looks like the code expects the extruder to be a stepper motor, and expects the stepper_axis to be set.  I don't understand the system well enough, though, to know how to set it.
