### ISSUE TITLE
Cannot run on OS X.10.1 with Oracle Java 1.8.0_25

### ISSUE THREAD

**Issue by alecthegeek** [makerbot/ReplicatorG#294]
OS X 10.10.1
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Running `/Applications/ReplicatorG.app/Contents/MacOS/ReplicatorG` give following output

[JavaAppLauncher Warning] Java application launched from bad stub. Relaunching in 32-bit, and tagging sub-processes to prefer 32-bit with $JAVA_ARCH=i386.
error in posix_spawn: 86
Dec 16, 2014 3:46:40 PM replicatorg.machine.MachineFactory load
SEVERE: Could not load machine 'The Replicator Dual' no machineNode found
java.lang.UnsatisfiedLinkError: /Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib: dlopen(/Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib, 1): no suitable image found.  Did find:
    /Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib: no matching architecture in universal wrapper thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib: dlopen(/Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib, 1): no suitable image found.  Did find:
    /Applications/ReplicatorG.app/Contents/Resources/Java/librxtxSerial.jnilib: no matching architecture in universal wrapper
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
    at replicatorg.app.util.serial.Serial.scanSerialNames(Serial.java:96)
    at replicatorg.app.ui.MainWindow.reloadSerialMenu(MainWindow.java:707)
    at replicatorg.app.ui.MainWindow.buildMachineMenu(MainWindow.java:1263)
    at replicatorg.app.ui.MainWindow.<init>(MainWindow.java:334)
    at replicatorg.app.Base$2.run(Base.java:655)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)......

**Comment by hermanbanken** [comment]
See https://github.com/jetty840/ReplicatorG/issues/63
