### ISSUE TITLE
Saving files on ubuntu creates unreadable files

### ISSUE THREAD

**Issue by Steamrunner** [makerbot/ReplicatorG#95]
Hello,

I'm running Ubuntu 10.04 LTS stable. When using the ReplicatorG 0018 to save STL files, these files become unreadable. And they cannot be read back into the program. ReplicatorG 0017 or blender are also unable to read files saved by ReplicatorG 0018. 

Error in ReplicatorG:
[16:28:33] Error loading model /home/koen/Bureaublad/MakerBot/3D logo_v1.stl
[16:28:33] java.lang.NullPointerException

Error from command window:
28-jul-2010 16:30:07 replicatorg.app.ui.MainWindow$38 run
INFO: Loading /home/koen/Bureaublad/MakerBot/3D logo_v3.stl
Load file : /home/koen/Bureaublad/MakerBot/3D logo_v3.gcode
28-jul-2010 16:30:08 replicatorg.app.ui.modeling.PreviewPanel setScene
INFO: /home/koen/Bureaublad/MakerBot/3D logo_v3.stl
28-jul-2010 16:30:08 org.j3d.loaders.stl.STLASCIIParser2 readObjectStats
INFO: Got name Default
28-jul-2010 16:30:08 org.j3d.loaders.stl.STLASCIIParser2 readObjectStats
INFO: Parsed object name[Default] facets 2578
28-jul-2010 16:30:08 replicatorg.model.BuildModel loadShape
SEVERE: Error loading model /home/koen/Bureaublad/MakerBot/3D logo_v3.stl
java.lang.NumberFormatException: For input string: "0,000000e+00"
    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1242)
    at java.lang.Double.parseDouble(Double.java:527)
    at org.j3d.loaders.stl.STLASCIIParser2.readVector(STLASCIIParser2.java:64)
    at org.j3d.loaders.stl.STLASCIIParser2.getNextFacet(STLASCIIParser2.java:75)
    at org.j3d.loaders.stl.STLFileReader.getNextFacet(STLFileReader.java:164)
    at org.j3d.renderer.java3d.loaders.STLLoader.createScene(STLLoader.java:171)
    at org.j3d.renderer.java3d.loaders.STLLoader.load(STLLoader.java:118)
    at org.j3d.renderer.java3d.loaders.STLLoader.load(STLLoader.java:86)
    at replicatorg.model.BuildModel.loadShape(BuildModel.java:53)
    at replicatorg.model.BuildModel.getShape(BuildModel.java:44)
    at replicatorg.app.ui.modeling.EditingModel.makeShape(EditingModel.java:77)
    at replicatorg.app.ui.modeling.EditingModel.getGroup(EditingModel.java:132)
    at replicatorg.app.ui.modeling.PreviewPanel.setScene(PreviewPanel.java:83)
    at replicatorg.app.ui.modeling.PreviewPanel.setModel(PreviewPanel.java:71)
    at replicatorg.app.ui.MainWindow.setModel(MainWindow.java:1273)
    at replicatorg.app.ui.MainWindow.handleOpen2(MainWindow.java:1956)
    at replicatorg.app.ui.MainWindow.checkModified2(MainWindow.java:1804)
    at replicatorg.app.ui.MainWindow.checkModified(MainWindow.java:1725)
    at replicatorg.app.ui.MainWindow$38.run(MainWindow.java:1921)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:602)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)
28-jul-2010 16:30:08 replicatorg.app.ui.MainWindow error
SEVERE: null
java.lang.NullPointerException
    at replicatorg.app.ui.modeling.EditingModel.makeShape(EditingModel.java:79)
    at replicatorg.app.ui.modeling.EditingModel.getGroup(EditingModel.java:132)
    at replicatorg.app.ui.modeling.PreviewPanel.setScene(PreviewPanel.java:83)
    at replicatorg.app.ui.modeling.PreviewPanel.setModel(PreviewPanel.java:71)
    at replicatorg.app.ui.MainWindow.setModel(MainWindow.java:1273)
    at replicatorg.app.ui.MainWindow.handleOpen2(MainWindow.java:1956)
    at replicatorg.app.ui.MainWindow.checkModified2(MainWindow.java:1804)
    at replicatorg.app.ui.MainWindow.checkModified(MainWindow.java:1725)
    at replicatorg.app.ui.MainWindow$38.run(MainWindow.java:1921)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:226)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:602)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:275)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:200)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:190)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:185)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:177)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:138)

**Comment by Steamrunner** [comment]
Some further examination showed that this problem only occurs when using openJDK and not when running sun-java. openJDK is the recommended platform however in your documentation.

**Comment by charlespax** [comment]
If this is still an issue with ReplicatorG 21, please resubmit bug report.
